version: '3.8'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
  cache:
    image: redis:7.2.0
